### PR TITLE
AbstractResultSet implements JsonSerializable

### PR DESCRIPTION
**Pull request by vaclavvanik**
Since the requirements for PHP increased we could benefit from [JsonSerializable](http://php.net/manual/en/jsonserializable.jsonserialize.php).

### CODE REVIEW

**Comment by Ocramius** [comment]
This seems to mix concerns, IMO. Serialization of resultsets is usually done via hydrators or via a simple `json_serialize(iterator_to_array($resultSet))`, which indicates the will to actually unroll the entire iterator.

Additionally, you may be running out of memory when treating an iterable object as an array, assuming it will just "fit".

I'll leave this decision to someone else, but I'm 👎 on this :-\

**Comment by vaclavvanik** [comment]
@Ocramius thanks for your opinions. My idea to create this PR was that I can spare call of `json_encode(iterator_to_array($resultSet))`,  which still can be used. E.g.:

```
return new JsonResponse(['items' => $resultSet]);
```



Out of memory problem with encoding "big data" imo occurs anyway. Unfortunately `toArray()` has the same problem.

**Comment by turrsis** [comment]
We can serialize to `XML` too, and, perhaps, to other formats.
Therefore this should be do via external objects.

**Comment by mwillbanks** [comment]
I'm going to close this citing that we would be fixing concerns and the goal of the ResultSet is not to have this logic contained therein.  It is actually more beneficial to have the Hydrator do this work OR as @Ocramius has stated the simple difference.  When we then look at the comment about having XML and the several other formats this could start to cause a competing amount of code to come into the ResultSet that is not entirely necessary.

**Pull request closed without merging**
