### PR TITLE
Fix a sequence name with double quotes for PostgreSQL to preserve nam…

### PR DESCRIPTION
**Pull request by alexsds**
…e registry when try to get last sequence id
See description for bug (https://github.com/zendframework/zendframework/pull/6222)

### CODE REVIEW

**Comment by alexsds** [comment]
hello @weierophinney. Please send feedback

**Comment by mwillbanks** [comment]
@alexsds This has not been reviewed because it breaks the unit tests, fix the tests so that it passes and we can then review for inclusion.

**Comment by alexsds** [comment]
@mwillbanks fixed tests

**Comment by ezimuel** [comment]
@alextech this PR is covered by your https://github.com/zendframework/zend-db/pull/187 ?

**Comment by alextech** [comment]
@ezimuel yes

**Comment by ezimuel** [comment]
Closing in favor of #187

**Pull request closed without merging**
