### PR TITLE
Changed copyright to 2017

### PR DESCRIPTION
**Pull request by chr-is**

### CODE REVIEW

**Comment by ezimuel** [comment]
@chr-is as reported in #218 can you send this PR against master? Develop should be used only for new features. Thanks!

**Comment by malukenho** [comment]
@ezimuel I guess it's invalid as per @weierophinney explanation in here https://github.com/zendframework/zend-expressive/pull/418#issuecomment-270484049

**Comment by ezimuel** [comment]
@malukenho thanks, I didn't notice that. @chr-is we don't need to update the copyright date in all the files, only in `LICENSE.md`. Can you create a new PR with only this change? Thanks!

**Comment by chr-is** [comment]
@ezimuel see #225

**Pull request closed without merging**
