### PR TITLE
[test] Provide a Vagrantfile for online tests

### PR DESCRIPTION
**Pull request by Maks3w**

### CODE REVIEW

**Comment by Maks3w** [comment]
This should be merged even with the failling test because it's a real failure.

**Comment by Maks3w** [comment]
@ralphschindler Could you review this?

**Comment by akrabat** [comment]
Is there a PR that fixes the test failure?

**Comment by Maks3w** [comment]
@ralphschindler had an idea of fix this using traits. I don't have more information about this. 

Anyway the PR should be merged.

**Pull request closed without merging**
