### PR TITLE
Enable use of MetadataFeature with TableIdentifier

### LINKED ISSUE #391: TableGateway used with TableIdentifier and MetadataFeature
- [x] I was not able to find an [open](https://github.com/zendframework/zend-db/issues?q=is%3Aopen) or [closed](https://github.com/zendframework/zend-db/issues?q=is%3Aclosed) issue matching what I'm seeing.
 - [x] This is not a question. (Questions should be asked on [slack](https://zendframework.slack.com/) ([Signup for Slack here](https://zendframework-slack.herokuapp.com/)) or our [forums](https://discourse.zendframework.com/).)

Provide a narrative description of what you are trying to accomplish.

### Code to reproduce the issue

When using TableGateway with TableIdentifier and MetadataFeature, I have an error message (see below).
My database is *PostgreSQL 10.8*.

```php
$test = new TableGateway(new TableIdentifier('test', 'public'), $adapter, new MetadataFeature());
```

### Expected results

I'm expecting the same result that I get with the following code (that one works):

```php
$test = new TableGateway('test', $adapter, new MetadataFeature());
```

### Actual results

Error message:
```
ErrorException: Illegal offset type in isset or empty in file vendor/zendframework/zend-db/src/Metadata/Source/AbstractSource.php on line 449
```

See https://github.com/zendframework/zend-db/blob/master/src/Metadata/Source/AbstractSource.php#L449

### PR DESCRIPTION
**Pull request by jbelien**
Fix #391

Provide a narrative description of what you are trying to accomplish:

- [x] Are you fixing a bug?
  - [x] Detail how the bug is invoked currently (see #391).
  - [x] Detail the original, incorrect behavior (see #391).
  - [x] Detail the new, expected behavior (see #391).
  - [x] Base your feature on the `master` branch, and submit against that branch.
  - [x] Add a regression test that demonstrates the bug, and proves the fix.
  - [ ] Add a `CHANGELOG.md` entry for the fix.

### CODE REVIEW

**Comment by jbelien** [comment]
@webimpress Sure, I probably can do that but never tried to add a test on a ZendFramework project.

Do I "just" have to add a new test that uses MetadataFeature with TableIdentifier in https://github.com/zendframework/zend-db/blob/master/test/unit/TableGateway/Feature/MetadataFeatureTest.php ?

**Comment by webimpress** [comment]
@jbelien Cool! If you have any questions you can catch me on [ZF slack](https://zendframework.slack.com)

**Comment by jbelien** [comment]
@webimpress I apparently can't join the ZF Slack. When I try to login, it says that "I need to ask the workspace admin to invite me.".

You didn't reply my question:
> Do I "just" have to add a new test that uses MetadataFeature with TableIdentifier in `TableGateway/Feature/MetadataFeatureTest.php` ?

Thanks!

**Comment by webimpress** [comment]
@jbelien 
sorry, to join the slack you have to follow this link:
https://zendframework-slack.herokuapp.com

> Do I "just" have to add a new test that uses MetadataFeature with TableIdentifier in https://github.com/zendframework/zend-db/blob/master/test/unit/TableGateway/Feature/MetadataFeatureTest.php ?

Yes, that's correct, as you are modifying `MetadataFeature.php` tests should be added in the corresponding test class.

**Comment by jbelien** [comment]
Thank you so much @webimpress for your help! ❤️

**Comment by michalbundyra** [comment]
Thanks, @jbelien!

**Pull request merged**
