### PR TITLE
Merge redundant `if` statements

### PR DESCRIPTION
**Pull request by malukenho**

### CODE REVIEW

**Comment by ezimuel** [comment]
@malukenho please provide unit test, thanks!

**Comment by Ocramius** [comment]
@ezimuel no execution path changes - only compacted the conditionals.

**Comment by Ocramius** [comment]
@malukenho please change target to `develop`

**Comment by malukenho** [comment]
@Ocramius changed

**Comment by Ocramius** [comment]
👍

**Pull request merged**
