### PR TITLE
Fix loading constraint data from Oracle

### PR DESCRIPTION
**Pull request by vixriihi**
This Fixes loading constraint data from Oracle database

### CODE REVIEW

**Comment by Maks3w** [comment]
Need unit test

**Comment by vixriihi** [comment]
I cannot add test before August

**Comment by Maks3w** [comment]
I think this will closed then because there is no kind of explanation about what are you trying to fix

**Comment by weierophinney** [comment]
@vixriihi Re-open or submit a new pull request when you have time to create a unit test.

**Comment by vixriihi** [comment]
I'll add the unittests in another pr, but here is a small summary of what these chages would do. At the moment method loadConstraintData is not working at all in oracle and thats because there is [trailing semicolon](https://github.com/zendframework/zend-db/blob/master/src/Metadata/Source/OracleMetadata.php#L129) in the sql statement and because using your using reserved word [":table"](https://github.com/zendframework/zend-db/blob/master/src/Metadata/Source/OracleMetadata.php#L127) as variable

**Comment by vixriihi** [comment]
Added the missing unittest and made a new PR https://github.com/zendframework/zend-db/pull/34

**Pull request closed without merging**
