### PR TITLE
Short named parameters

### PR DESCRIPTION
**Pull request by hamilok**
Fixed bug "ORA-00972: identifier is too long"

### CODE REVIEW

**Comment by hamilok** [comment]
Before:
SELECT
  COUNT(1) AS "C"
FROM (
  SELECT
    "SYS_USER"."ID" AS "ID",
    "SYS_USER"."EMAIL" AS "EMAIL",
    "SYS_USER"."STATUS" AS "STATUS",
    TO_CHAR(LAST_SIGNIN_TIME, **:subselect1subselect1LAST_SIGNIN_TIME1**) AS "LAST_SIGNIN_TIME",
    TO_CHAR(CREATED_TIME, **:subselect1subselect1CREATED_TIME1**) AS "CREATED_TIME"
  FROM
    "SYS_USER"
  WHERE
    "LAST_SIGNIN_TIME" > SYSDATE - NUMTODSINTERVAL(**:subselect1subselect1where1subpart1**, **:subselect1subselect1where1subpart2**)
    AND
    "CREATED_TIME" > SYSDATE - NUMTODSINTERVAL(**:subselect1subselect1where1subpart3**, **:subselect1subselect1where1subpart4**
  )) "original_select"

After:
SELECT
  COUNT(1) AS "C"
FROM (
  SELECT
    "SYS_USER"."ID" AS "ID",
    "SYS_USER"."EMAIL" AS "EMAIL",
    "SYS_USER"."STATUS" AS "STATUS",
    TO_CHAR(LAST_SIGNIN_TIME, **:ss1ss1LAST_SIGNIN_TIME1**) AS "LAST_SIGNIN_TIME",
    TO_CHAR(CREATED_TIME, **:ss1ss1CREATED_TIME1**) AS "CREATED_TIME"
  FROM
    "SYS_USER"
  WHERE
    "LAST_SIGNIN_TIME" > SYSDATE - NUMTODSINTERVAL(**:ss1ss1where1sp1**, **:ss1ss1where1sp2**)
    AND
    "CREATED_TIME" > SYSDATE - NUMTODSINTERVAL(**:ss1ss1where1sp3**, **:ss1ss1where1sp4**
  )) "original_select"

**Comment by webimpress** [comment]
@hamilok Please check travis build:
https://travis-ci.org/zendframework/zend-db/builds/342271399?utm_source=github_status&utm_medium=notification

It's failing because of your change. Could you please fix them and add your test case?

**Comment by hamilok** [comment]
@Ocramius please, merge it

**Comment by Ocramius** [comment]
This seems to patch just the prefix/suffix to shorten it, but adding multiple sub-selects will lead to the same issue anyway...

**Comment by hamilok** [comment]
Very likely, but now even with one "subselect" there is a problem.

**Comment by ezimuel** [comment]
@Ocramius are you sure that this doesn't fix also multiple sub-selects use cases?

**Comment by Ocramius** [comment]
@ezimuel yes: this is basically "let's fix an overflow by making the payload size smaller", instead of fixing the actual overflow.

**Comment by ezimuel** [comment]
@hamilok you mentioned bug ORA-00972, can you add more information on this? I don't see any issue opened with this reference. Thanks!

**Comment by ezimuel** [comment]
@Ocramius I see, anyway it's still a fix to reduce the issue. A better solution will be to rewrite the string parameters using some internal table reference, as I did [here](https://github.com/zendframework/zend-db/pull/304/commits/b590f483bda5376f87ac078722233ef0e12cd05d#diff-c69ae19cb12208fed7d85c26e187d393R189) for #304.

**Comment by Ocramius** [comment]
> anyway it's still a fix to reduce the issue

I'm extremely vary of anything that doesn't fix the issue at the source, so I can't agree with going with the current solution. The approach taken in #304 looks more appropriate.

**Comment by ezimuel** [comment]
@Ocramius you right, I'm closing this in favor of alternative solution based on #304 approach. @hamilok  can you have a look at this solution and propose a new PR? Thanks anyway for your contribution here!

**Pull request closed without merging**
