### PR TITLE
MySQL "ADD COLUMN ... AFTER ..." support

### PR DESCRIPTION
**Pull request by nanawel**
ZF1 supports MySQL syntax allowing to add a column AFTER another one in an ALTER TABLE statement. ZF2 does not. This PR is intended to fix that.

### CODE REVIEW

**Comment by alextech** [comment]
I want to say "needs a test" but looking at the decorator, there are no existing tests for it where you could have added it. Yet it must be done :) Can you please create an `AlterTableDecoratorTest` in the same place and same way `CreateTableDecoratorTest` and add your option in there? (I could assist if unsure how)

**Comment by nanawel** [comment]
Sure, I'll add it to the PR.

**Comment by alextech** [comment]
Thank you :)

**Comment by nanawel** [comment]
Yes, this is my assumption too.

**Comment by nanawel** [comment]
New test class included, no error detected on PHPUnit on my instance.

**Comment by ezimuel** [comment]
@nanawel thanks for your contribution!

**Pull request merged**
